#include "fff_lin.h"

DEFINE_FAKE_VOID_FUNC(lin_pid_response_callback_handler, lin_lld_event_id, l_u8);
DEFINE_FAKE_VALUE_FUNC(l_u8, lin_lld_init);
DEFINE_FAKE_VALUE_FUNC(l_u8, lin_lld_deinit);
DEFINE_FAKE_VALUE_FUNC(l_u8, lin_lld_get_status);
DEFINE_FAKE_VALUE_FUNC(l_u8, lin_lld_get_state);
DEFINE_FAKE_VOID_FUNC(lin_lld_tx_wake_up);
DEFINE_FAKE_VOID_FUNC(lin_lld_int_enable);
DEFINE_FAKE_VALUE_FUNC(l_u8, lin_lld_int_disable);
DEFINE_FAKE_VOID_FUNC(lin_lld_ignore_response);
DEFINE_FAKE_VOID_FUNC(lin_lld_set_low_power_mode);
DEFINE_FAKE_VALUE_FUNC(l_u8, lin_lld_set_response, l_u8);
DEFINE_FAKE_VALUE_FUNC(l_u8, lin_lld_rx_response, l_u8);
DEFINE_FAKE_VOID_FUNC(lin_lld_mcu_reset);
DEFINE_FAKE_VOID_FUNC(lin_lld_timer_init);
DEFINE_FAKE_VALUE_FUNC(l_u8, lin_checksum, l_u8 *, l_u8);
DEFINE_FAKE_VALUE_FUNC(l_u8, lin_process_parity, l_u8, l_u8);
// DEFINE_FAKE_VOID_FUNC(lin_lld_sci_isr, uint32_t, uint32_t);
DEFINE_FAKE_VALUE_FUNC(l_bool, l_sys_init);
DEFINE_FAKE_VALUE_FUNC(l_bool, l_ifc_init);
DEFINE_FAKE_VOID_FUNC(l_ifc_wake_up);
DEFINE_FAKE_VOID_FUNC(l_ifc_rx);
DEFINE_FAKE_VOID_FUNC(l_ifc_tx);
DEFINE_FAKE_VALUE_FUNC(l_u16, l_ifc_read_status);
DEFINE_FAKE_VOID_FUNC(l_ifc_aux);
DEFINE_FAKE_VALUE_FUNC(l_u16, l_sys_irq_disable);
DEFINE_FAKE_VOID_FUNC(l_sys_irq_restore);
DEFINE_FAKE_VOID_FUNC(ld_init);
DEFINE_FAKE_VOID_FUNC(ld_put_raw, const l_u8 *const);
DEFINE_FAKE_VOID_FUNC(ld_get_raw, l_u8 *const);
DEFINE_FAKE_VALUE_FUNC(l_u8, ld_raw_tx_status);
DEFINE_FAKE_VALUE_FUNC(l_u8, ld_raw_rx_status);
DEFINE_FAKE_VOID_FUNC(ld_send_message, l_u16, const l_u8 *const);
DEFINE_FAKE_VOID_FUNC(ld_receive_message, l_u16 *const, l_u8 *const);
DEFINE_FAKE_VALUE_FUNC(l_u8, ld_tx_status);
DEFINE_FAKE_VALUE_FUNC(l_u8, ld_rx_status);
DEFINE_FAKE_VALUE_FUNC(l_u8, diag_get_flag, l_u8);
DEFINE_FAKE_VOID_FUNC(diag_clear_flag, l_u8);
DEFINE_FAKE_VALUE_FUNC(l_bool, l_ifc_connect, l_ifc_handle);
DEFINE_FAKE_VALUE_FUNC(l_bool, l_ifc_disconnect, l_ifc_handle);
